### ISSUE TITLE
Add info that a redis server is needed to be running

### ISSUE THREAD

**Issue by cocampbe** [trondhindenes/flansible#4]
I think adding that a redis server needs to be installed/running should be added to the README. I would guess that most mortals are not familiar with redis. That in fact was the case for myself. It took awhile to understand what the python redis module did. After looking through the modules docs, I ended up installing a redis server. Had I known prior to that, it would have saved me some time. 

Also, thanks for making the project. It's exactly what a colleague, and myself, were looking for.

**Comment by trondhindenes** [comment]
Thanks for the feedback! It states pretty clearly that "Celery requires a datastore, either Redis or RabbitMQ.", but I still see what you mean. I guess it could be interpreted as optional since the explicit string is under the "optional" heading. I'll get this updated. Glad you got it working in the end, and thanks for the feedback!

**Comment by trondhindenes** [comment]
I've (hopefully) clarified the requirements, so closing this.
